### ISSUE TITLE
Feature Request: Set env var from YAML for local debugging

### ISSUE THREAD

**Issue by pllim** [jbcurtin/bert-etl#12]
Currently, when run locally using Docker and `redis`, environment variables from `bert-etl.yaml` are not set automatically. Example:
```yaml
every_lambda:
  environment:
    DEBUG: "false"
    HOME: /tmp
    AWSBUCKETNAME: mybucket
```

Note to self: When this is implemented, will need to swap out the YAML between testing and deployment, as appropriate.

**Comment by jbcurtin** [comment]
This is currently possible with local testing now. Would you mind confirming?

**Comment by pllim** [comment]
Finally got a chance to try but got a traceback:

```
$ redis_docker
$ bert-runner.py -m app_all_lambdas -f
Traceback (most recent call last):
  File ".../bin/bert-runner.py", line 11, in <module>
    load_entry_point('bert-etl==0.4.20', 'console_scripts', 'bert-runner.py')()
  File ".../lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File ".../lib/python3.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File ".../lib/python3.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File ".../lib/python3.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'bert.factory'
```
