### ISSUE TITLE
AttributeError: 'Deployment' object has no attribute 's3_bucket'

### ISSUE THREAD

**Issue by pllim** [jbcurtin/bert-etl#15]
Using the latest `master`:
```
bert-deploy.py -m app_all_lambdas -s aws-lambda 
```
gives this traceback:
```
2019-09-24 01:23:52,037 - bert.constants - INFO - DEBUG[True]
Traceback (most recent call last):
  File ".../bin/bert-deploy.py", line 11, in <module>
    load_entry_point('bert-etl==0.4.19', 'console_scripts', 'bert-deploy.py')()
  File ".../bert/deploy/factory.py", line 104, in run_from_cli
    deploy_service(options)
  File ".../bert/deploy/factory.py", line 39, in deploy_service
    jobs: typing.Dict[str, typing.Any] = bert_utils.map_jobs(jobs)
  File ".../bert/utils.py", line 70, in map_jobs
    bert_shortcuts.head_bucket_for_existance(deployment_config.s3_bucket)
AttributeError: 'Deployment' object has no attribute 's3_bucket'
```

**Comment by jbcurtin** [comment]
This error is handled more gracefully now. Upgrade to `0.4.20` or latest `master` and it should go away
