### ISSUE TITLE
Deployed Lambda cannot import Numpy

### ISSUE THREAD

**Issue by pllim** [jbcurtin/bert-etl#9]
I ran `bert-deploy.py` from inside a `conda` environment and installed Numpy from conda's `defaults` channel as such (note that same problem occurs if I install `numpy` from `conda-forge` as well):

```
# packages in environment at .../miniconda/envs/bert:
#
# Name                    Version                   Build  Channel
numpy                     1.16.4           py37h7e9f1db_0  
numpy-base                1.16.4           py37hde5b4d6_0  
```

When deployed to Lambda, the function provides this traceback in "details":
```
{
  "errorMessage": "Numpy version 1.13.0 or later must be installed to use Astropy",
  "errorType": "ImportError",
  "stackTrace": [
    "  File \"/var/task/bert_etl-0.4.16-py3.7.egg/bert/binding.py\", line 81, in _wrapper\n    return wrapped_func(*args, **kwargs)\n",
    "  File \"/var/task/bert_tess_fullframe_main.py\", line 44, in bert_tess_fullframe_main\n    from astroquery.mast import Observations\n",
    "  File \"/var/task/astroquery-0.3.10.dev5705-py3.7.egg/astroquery/__init__.py\", line 12, in <module>\n    from ._astropy_init import *\n",
    "  File \"/var/task/astroquery-0.3.10.dev5705-py3.7.egg/astroquery/_astropy_init.py\", line 29, in <module>\n    from astropy.config.configuration import (\n",
    "  File \"/var/task/astropy/__init__.py\", line 122, in <module>\n    _check_numpy()\n",
    "  File \"/var/task/astropy/__init__.py\", line 117, in _check_numpy\n    raise ImportError(msg)\n"
  ]
}
```
And this in "log details":
```
START RequestId: ... Version: $LATEST
[INFO]	2019-09-09T18:56:53.706Z	...	Bert Queue Type[QueueTypes.Dynamodb]

2019-09-09 18:56:53,706 - bert.utils - INFO - Bert Queue Type[QueueTypes.Dynamodb]
[INFO]	2019-09-09T18:56:53.706Z	...	QueueType[QueueTypes.Dynamodb]

2019-09-09 18:56:53,706 - bert_tess_fullframe_main.MainProcess - INFO - QueueType[QueueTypes.Dynamodb]
[ERROR] ImportError: Numpy version 1.13.0 or later must be installed to use Astropy
Traceback (most recent call last):
  File "/var/task/bert_etl-0.4.16-py3.7.egg/bert/binding.py", line 81, in _wrapper
    return wrapped_func(*args, **kwargs)
  File "/var/task/bert_tess_fullframe_main.py", line 44, in bert_tess_fullframe_main
    from astroquery.mast import Observations
  File "/var/task/astroquery-0.3.10.dev5705-py3.7.egg/astroquery/__init__.py", line 12, in <module>
    from ._astropy_init import *
  File "/var/task/astroquery-0.3.10.dev5705-py3.7.egg/astroquery/_astropy_init.py", line 29, in <module>
    from astropy.config.configuration import (
  File "/var/task/astropy/__init__.py", line 122, in <module>
    _check_numpy()
  File "/var/task/astropy/__init__.py", line 117, in _check_numpy
    raise ImportError(msg)
END RequestId: ...
REPORT RequestId: ...	Duration: 42.57 ms	Billed Duration: 100 ms	Memory Size: 512 MB	Max Memory Used: 86 MB	Init Duration: 947.19 ms	
XRAY TraceId: ...	SegmentId: ...	Sampled: false	
```
When downloading the deployed ZIP and trying to import `numpy` shipped with it, it complains about:
```
>>> from numpy._distributor_init import _mklinit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../numpy/__init__.py", line 140, in <module>
    from . import _distributor_init
  File ".../numpy/_distributor_init.py", line 34, in <module>
    from . import _mklinit
ImportError: libmkl_rt.so: cannot open shared object file: No such file or directory
```
In the conda environment, this SO file is found in `.../miniconda/envs/bert/lib`, where `bert` is the environment name. There are other `libmkl_*.so` files in that directory as well.

**Comment by jbcurtin** [comment]
I've implemented `requirements` in `bert-etl.yaml`. This may take care of this problem, would you mind testing it?

```
every_lambda:
  memory_size: 128
  requirements:
    - numpy==1.17.1
```

**Comment by pllim** [comment]
Fixed in `master`. Thanks!
